#pragma once

#define LOG_IN 1
#define SIGN_UP 2
#define SIGN_UP_OFFSET 10
#define PLAYER 3
#define RESPONSE 4
#define FRAME_DATA 6
#define CAN_INIT_CHARACTER 7
#define REQUEST_FRAMEDATAS 8
#define PER_FRAME_TIME 30000
#define HEAD_LENGTH 3
#define LENGTH_BASE 100 
#define BUFF_SIZE 10240
#define DEFAULT_PORT 17000
#define BACKLOG 100
#define MAX_EVENTS 1024
#define HEAD_LENGTH 3
#define ONE_ROOM 1
#define MAX_FRAMEDATAS 100000


